import { useEffect, useMemo, useRef, useState } from 'react'
import { BookOpen, ChevronRight, CircleHelp, CloudDownload, FileCheck2, FolderOpen, Gauge, LayoutDashboard, LockKeyhole, Menu, MoreHorizontal, ScanText, Settings2, ShieldCheck, SlidersHorizontal, UploadCloud } from 'lucide-react'
import { AnalysisPage, ComparisonPage, Dashboard, DocumentsPage, LoadingState, ProcessingPage, ResultPage, SpecificationPage, StructurePage, UploadPage, ValidationPage } from './components'
import { api } from './services/api'
import type { PresetResponse, PresetView, RequestState, Screen, SessionState, StatusResponse } from './types'
import './index.css'

const navItems: { id: Screen; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'upload', label: 'Upload manuscript', icon: UploadCloud }, { id: 'analysis', label: 'Document analysis', icon: ScanText }, { id: 'structure', label: 'Structure detection', icon: BookOpen }, { id: 'specification', label: 'Publication spec', icon: SlidersHorizontal }, { id: 'processing', label: 'Processing', icon: Gauge }, { id: 'validation', label: 'Validation', icon: ShieldCheck }, { id: 'comparison', label: 'Before / after', icon: FileCheck2 }, { id: 'result', label: 'Result', icon: CloudDownload },
]
const initialSession: SessionState = { documentId: null, filename: '', fileSize: 0, uploadState: 'idle', analysisState: 'idle', formatState: 'idle', processingState: 'idle', analysis: null, status: null, report: null, presets: [], selectedPreset: null, selectedModel: 'logistic_regression', presetState: 'idle', presetError: null, error: null, backendReady: false }

function App() {
  const [screen, setScreen] = useState<Screen>('dashboard'); const [mobileNav, setMobileNav] = useState(false); const [session, setSession] = useState<SessionState>(initialSession); const [file, setFile] = useState<File | null>(null); const [dragging, setDragging] = useState(false); const [downloadState, setDownloadState] = useState<RequestState>('idle'); const fileInput = useRef<HTMLInputElement>(null); const pollingTimer = useRef<number | null>(null); const workflowVersion = useRef(0)
  const fileSize = useMemo(() => file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : '', [file])

  const loadPresets = async () => {
    setSession((current) => ({ ...current, presetState: 'loading', presetError: null }))
    try {
      const response = await api.getPresets()
      const presets = response.profiles.map(toPresetView)
      setSession((current) => ({ ...current, presets, selectedPreset: current.selectedPreset && presets.some((preset) => preset.name === current.selectedPreset?.name) ? current.selectedPreset : presets[0] ?? null, presetState: 'success', presetError: null }))
    } catch (error) {
      setSession((current) => ({ ...current, presetState: 'error', presetError: toMessage(error) }))
    }
  }

  useEffect(() => {
    let active = true
    const initialize = async () => {
      const health = api.health().then(() => {
        if (active) setSession((current) => ({ ...current, backendReady: true }))
      }).catch((error) => {
        if (active) setSession((current) => ({ ...current, backendReady: false, error: toMessage(error) }))
      })
      const presets = loadPresets()
      await Promise.allSettled([health, presets])
    }
    void initialize()
    return () => { active = false }
  }, [])
  useEffect(() => () => { workflowVersion.current += 1; if (pollingTimer.current !== null) window.clearTimeout(pollingTimer.current) }, [])

  const navigate = (next: Screen) => { if (['analysis', 'structure', 'specification', 'processing', 'validation', 'comparison', 'result'].includes(next) && (!session.documentId || (['validation', 'comparison', 'result'].includes(next) && !session.report))) { setScreen(session.documentId ? 'analysis' : 'upload'); return } setScreen(next); setMobileNav(false) }
  const chooseFile = (candidate?: File) => { if (!candidate) return; if (!candidate.name.toLowerCase().endsWith('.docx') || candidate.size > 100 * 1024 * 1024) { setSession((current) => ({ ...current, error: 'Choose a readable DOCX file smaller than 100 MB.', uploadState: 'error' })); return } setFile(candidate); setSession((current) => ({ ...current, ...initialSession, backendReady: current.backendReady, presets: current.presets, selectedPreset: current.selectedPreset, filename: candidate.name, fileSize: candidate.size, error: null, uploadState: 'idle' })); setScreen('upload') }
  const analyze = async () => { if (!file) return; setSession((current) => ({ ...current, uploadState: 'loading', analysisState: 'loading', error: null })); try { const upload = await api.uploadDocument(file); setSession((current) => ({ ...current, documentId: upload.document_id, filename: upload.filename, fileSize: upload.size, uploadState: 'success', error: null })); const analysis = await api.analyzeDocument(upload.document_id, session.selectedModel); setSession((current) => ({ ...current, documentId: upload.document_id, filename: upload.filename, fileSize: upload.size, uploadState: 'success', analysisState: 'success', analysis, error: null })); setScreen('analysis') } catch (error) { setSession((current) => ({ ...current, uploadState: 'error', analysisState: 'error', error: toMessage(error) })) } }
  const applyFormat = async () => { if (!session.documentId || !session.selectedPreset) return; const documentId = session.documentId; const version = ++workflowVersion.current; if (pollingTimer.current !== null) window.clearTimeout(pollingTimer.current); setSession((current) => ({ ...current, formatState: 'loading', processingState: 'loading', status: null, report: null, error: null })); setScreen('processing'); try { const status = await api.formatDocument(documentId, session.selectedPreset.name, session.selectedModel); if (version !== workflowVersion.current) return; setSession((current) => ({ ...current, status })); if (status.status === 'failed') throw new Error(status.error ?? 'Formatting failed.'); if (status.status === 'completed') { await finishFormatting(documentId, status, version); return } await pollUntilComplete(documentId, version) } catch (error) { if (version !== workflowVersion.current) return; let report = null; try { report = await api.getDocumentReport(documentId) } catch { /* Keep the status error when no report is available. */ } setSession((current) => ({ ...current, formatState: 'error', processingState: 'error', report, error: toMessage(error) })); setScreen(report ? 'validation' : 'processing') } }
  const finishFormatting = async (documentId: string, status: StatusResponse, version: number) => { const report = await api.getDocumentReport(documentId); if (version !== workflowVersion.current) return; setSession((current) => ({ ...current, status, report, processingState: 'success', formatState: 'success', error: null })); setScreen('validation') }
  const pollUntilComplete = async (documentId: string, version: number) => { let cancelled = false; const poll = async (): Promise<void> => { const status = await api.getDocumentStatus(documentId); if (cancelled || version !== workflowVersion.current) return; setSession((current) => ({ ...current, status })); if (status.status === 'completed') { await finishFormatting(documentId, status, version); return } if (status.status === 'failed') throw new Error(status.error ?? 'Formatting failed.'); await new Promise<void>((resolve) => { pollingTimer.current = window.setTimeout(resolve, 800) }); return poll() }; try { await poll() } finally { cancelled = true; if (pollingTimer.current !== null) { window.clearTimeout(pollingTimer.current); pollingTimer.current = null } } }
  const download = async () => { if (!session.documentId) return; setDownloadState('loading'); try { const result = await api.downloadDocument(session.documentId); const url = URL.createObjectURL(result.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename; anchor.click(); URL.revokeObjectURL(url); setDownloadState('success') } catch (error) { setSession((current) => ({ ...current, error: toMessage(error) })); setDownloadState('error') } }
  const reset = () => { setFile(null); setSession({ ...initialSession, backendReady: session.backendReady, presets: session.presets, selectedPreset: session.presets[0] ?? null }); setScreen('upload') }
  const content = screen === 'dashboard' ? <Dashboard onNavigate={navigate} onUpload={() => navigate('upload')} backendReady={session.backendReady} /> : screen === 'upload' ? <UploadPage file={file} fileSize={fileSize} uploadState={session.uploadState} error={session.error} dragging={dragging} setDragging={setDragging} chooseFile={chooseFile} fileInput={fileInput} onAnalyze={() => void analyze()} /> : screen === 'analysis' ? <AnalysisPage analysis={session.analysis} filename={session.filename} analysisState={session.analysisState} onStructure={() => navigate('structure')} /> : screen === 'structure' ? <StructurePage elements={session.analysis?.elements ?? []} /> : screen === 'specification' ? <SpecificationPage presets={session.presets} selected={session.selectedPreset} selectedModel={session.selectedModel} presetState={session.presetState} presetError={session.presetError} onRetryPresets={() => void loadPresets()} onSelectModel={(selectedModel) => setSession((current) => ({ ...current, selectedModel }))} onSelect={(selectedPreset) => setSession((current) => ({ ...current, selectedPreset }))} onApply={() => void applyFormat()} loading={session.formatState === 'loading'} /> : screen === 'processing' ? <ProcessingPage status={session.status} error={session.error} /> : screen === 'validation' ? <ValidationPage report={session.report} onCompare={() => navigate('comparison')} onResult={() => navigate('result')} /> : screen === 'comparison' ? <ComparisonPage report={session.report} /> : screen === 'result' ? <ResultPage filename={session.filename} report={session.report} onAgain={reset} onDownload={() => void download()} downloadState={downloadState} /> : screen === 'documents' ? <DocumentsPage filename={session.filename} onUpload={() => navigate('upload')} /> : <LoadingState label="Choose a document workflow." />

  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><div className="brand-lockup"><div className="brand-mark"><BookOpen size={18} /></div><div><strong>DocXpress</strong><span>Editorial automation</span></div></div><div className="local-pill"><span className={`status-dot ${session.backendReady ? '' : 'offline-dot'}`} /> {session.backendReady ? 'LOCAL ENGINE READY' : 'LOCAL ENGINE OFFLINE'}</div><nav className="sidebar-nav" aria-label="Primary navigation"><span className="nav-label">Workspace</span>{navItems.map(({ id, label, icon: Icon }) => <button className={`nav-item ${screen === id ? 'active' : ''}`} key={id} onClick={() => navigate(id)}><Icon size={17} /><span>{label}</span>{screen === id && <ChevronRight className="nav-chevron" size={15} />}</button>)}<span className="nav-label nav-label-spaced">Library</span><button className="nav-item" onClick={() => navigate('documents')}><FolderOpen size={17} /><span>Documents</span></button><button className="nav-item" onClick={() => navigate('specification')}><Settings2 size={17} /><span>Templates</span></button></nav><div className="sidebar-footer"><div className="privacy-note"><LockKeyhole size={16} /><span><b>Your files stay here.</b><br />No cloud processing or tracking.</span></div><button className="help-button"><CircleHelp size={16} /> Help &amp; documentation</button><div className="version-line">DOCXPRESS / 0.1.0</div></div></aside>{mobileNav && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} /> }<main className="main-content"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14} /><b>{navItems.find((item) => item.id === screen)?.label ?? 'Documents'}</b></div><div className="topbar-actions"><span className="system-status"><span className={`status-dot ${session.backendReady ? '' : 'offline-dot'}`} /> {session.backendReady ? 'Local engine ready' : 'Engine unavailable'}</span><button className="icon-button" aria-label="More options"><MoreHorizontal size={19} /></button></div></header><div className="page-wrap">{content}</div></main></div>
}

function toPresetView(preset: PresetResponse): PresetView { const names: Record<string, [string, string, string]> = { hackathon_default: ['Default Publication', 'The default publication specification.', 'US Letter - 1.5 spacing'], trade: ['Trade Book', 'A measured book interior for long-form reading.', 'Trade profile'], fiction: ['Digest / Fiction', 'Warm typography for narrative manuscripts.', 'Fiction profile'], academic: ['Academic', 'Structured typography for research work.', 'Academic profile'] }; const [displayName, description, page] = names[preset.name] ?? [preset.name, 'Backend publication profile.', 'Backend profile']; return { ...preset, displayName, description, page } }
function toMessage(error: unknown) { return error instanceof Error ? error.message : 'An unexpected local processing error occurred.' }

export default App
